"""Fetch DF26 and lay it out so the existing scorers can read it.

DF26 is the benchmark this project's near-term work is measured against: 2,691
single-person public-speaking clips, 271 real and 2,420 generated by seven
modern systems including Veo 3.1, Kling 3.0, Grok Imagine 1.0 and Wan 2.6. Its
paper reports nine state-of-the-art detectors between 44.0 and 69.7 AUROC on it,
so it is the honest yardstick rather than a benchmark to win.

Two reasons it fits here without adaptation. Its real clips are content-matched
to its fakes, because each generation prompt was derived from the real clip's
own frames, which removes the confound that made the public `gen-videos-veo3`
set useless against our talking-head corpora. And it is single-person speaking,
so faces are present and the existing preprocessing works unchanged.

The upstream layout nests generator under scenario, `fake/<scenario>/<gen>/`.
This flattens it to `fake/<generator>/`, which is what `score_media_folder.py`
groups by, and keeps the scenario in a sidecar so the per-scenario analysis the
paper reports is still possible. Files are hard-linked where the filesystem
allows it and copied otherwise, so the layout costs no extra disk.

Access is gated and granted automatically on accepting the terms at
https://huggingface.co/datasets/DF26/DF26. Nothing here can bypass that.

    uv run python scripts/fetch_df26.py
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import shutil
import sys
from pathlib import Path


def _load_token(root: Path) -> str | None:
    env = root / ".env"
    if not env.is_file():
        return os.environ.get("HF_TOKEN")
    for line in env.read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            if key.strip() == "HF_TOKEN":
                return value.strip().strip('"')
    return os.environ.get("HF_TOKEN")


def _link_or_copy(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        return
    try:
        os.link(source, target)
    except OSError:
        shutil.copy2(source, target)


def main(argv: list[str] | None = None) -> int:
    from huggingface_hub import snapshot_download

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", type=Path, default=Path("data/DF26"))
    parser.add_argument("--repo", default="DF26/DF26")
    parser.add_argument(
        "--layout",
        type=Path,
        default=Path("data/df26-scored"),
        help="Where to build the real/ and fake/<generator>/ view.",
    )
    arguments = parser.parse_args(argv)

    token = _load_token(Path.cwd())
    if not token:
        print("No HF_TOKEN found in .env or the environment.")
        return 1

    print(f"downloading {arguments.repo}, about 3.6 GB")
    try:
        snapshot = snapshot_download(
            repo_id=arguments.repo,
            repo_type="dataset",
            token=token,
            local_dir=arguments.target,
        )
    except Exception as error:  # noqa: BLE001 - the message is the useful part
        message = str(error)
        if "gated" in message.lower() or "restricted" in message.lower():
            print(
                "Access is not granted yet. Accept the terms at "
                f"https://huggingface.co/datasets/{arguments.repo} and re-run. "
                "The gate is automatic, so it takes effect immediately."
            )
            return 2
        print(f"{type(error).__name__}: {message[:300]}")
        return 1

    root = Path(snapshot)
    videos = sorted(root.rglob("*.mp4"))
    print(f"{len(videos)} videos under {root}")
    if not videos:
        print("No video found, so the download did not contain what was expected.")
        return 1

    rows = []
    for path in videos:
        parts = path.relative_to(root).parts
        # fake/<scenario>/<generator>/<file>.mp4 and real/<scenario>/<file>.mp4
        kind = parts[0].lower()
        if kind.startswith("fake"):
            scenario = parts[1] if len(parts) > 3 else "unknown"
            generator = parts[-2]
            group = generator
            label = 1
            destination = arguments.layout / "fake" / generator / path.name
        else:
            scenario = parts[1] if len(parts) > 2 else "unknown"
            generator = "real"
            group = "real"
            label = 0
            destination = arguments.layout / "real" / path.name
        _link_or_copy(path, destination)
        rows.append(
            {
                "file": str(destination.relative_to(arguments.layout)).replace(
                    "\\", "/"
                ),
                "group": group,
                "generator": generator,
                "scenario": scenario,
                "label": label,
            }
        )

    sidecar = arguments.layout / "df26-index.csv"
    sidecar.parent.mkdir(parents=True, exist_ok=True)
    with sidecar.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=["file", "group", "generator", "scenario", "label"]
        )
        writer.writeheader()
        writer.writerows(rows)

    counts: dict[str, int] = {}
    scenarios: dict[str, int] = {}
    for row in rows:
        counts[row["group"]] = counts.get(row["group"], 0) + 1
        scenarios[row["scenario"]] = scenarios.get(row["scenario"], 0) + 1
    print(f"\nlaid out under {arguments.layout}")
    for group, count in sorted(counts.items(), key=lambda item: -item[1]):
        print(f"  {group:28} {count:5}")
    print(f"\nscenarios: {json.dumps(scenarios, sort_keys=True)}")
    print(f"index written to {sidecar}")
    print(
        "\nNext: uv run python scripts/score_media_folder.py --folder "
        f"{arguments.layout}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
